### ISSUE TITLE
Incorrect quote display

### ISSUE THREAD

**Issue by ghost** [AlphaNodes/redmine_messenger#10]
I'm using RocketChat and a quote inside a ticket description is displayed as `&#39` instead of quote.

**Comment by alexandermeindl** [comment]
I cannot reproduce this problem. Can you give my some information about your environment? Which Redmine version, which Ruby version do you use? And please use the latest redmine_messenger plugin version. Do you have Redmine plugins installed, which may conflict with it (e.g. CKEditor)?

**Comment by soohwa** [comment]
Thx for your answer :-)

Server:
* Debian Wheezy 64 bit
* Apache 2.2.22
* Passenger 5.1.8 (custom rebuild)
* Ruby 2.4.2
* Redmine 3.4.2
* Redmine Messenger 1.0.1 (Commits on Oct 15, 2017) : it is the only plugin I have installed.
* NodeJS 4.8.4
* Rocket.Chat 0.58.4

Client:
* Firefox ESR 52.4.0 (64 bits)

For custom rebuild I followed:
* https://www.admin-systeme.com/logiciel/installation-de-redmine-3-0-3-sous-debian-7-avec-passenger/
* https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-on-an-debian-7-0-wheezy-vps-using-rvm

I presume the escape come from ERB::Util.html_escape function because
```
&
<
>
'
```
are changed into
```
&amp;
&lt;
&gt;
&#39;
```

**Comment by ZerooCool** [comment]
' become &#39; with slack

The same with Debian 9 stable + RVM and Redmine 4.0.2
https://wiki.visionduweb.fr/index.php?title=Installer_Redmine_sur_Debian_avec_RVM

How i install the plugin
https://wiki.visionduweb.fr/index.php?title=Installer_Redmine_sur_Debian#redmine_messenger

Environment:
  Redmine version                4.0.3.stable
  Ruby version                   2.4.5-p335 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Filesystem                     
Redmine plugins:
  redmine_messenger              1.0.3

**Comment by alexandermeindl** [comment]
See #38 for fix.
