### ISSUE TITLE
Caractère ' become &#39; to Slack

### ISSUE THREAD

**Issue by ZerooCool** [AlphaNodes/redmine_messenger#38]
Text from issue redmine :
`Contenu vérifié après avoir récupéré l'accès.`

Text posted to Slack
`Contenu vérifié après avoir récupéré l&#39;accès.`

**Comment by ZerooCool** [comment]
I presume the escape come from ERB::Util.html_escape function because

&
<
>
'

are changed into

&amp;
&lt;
&gt;
&#39;

I suppose global variables can play, if UTF-8 is not properly configured on the server?

Do you have an idea to correct this problem?
(3 issues already open in total, for this problem of a special nature.)

**Comment by alexandermeindl** [comment]
This should be fixed in master now.

**Comment by alexandermeindl** [comment]
Hi ZerooCool,
can you check, if the problem is fixed with Slack? I do not have Slack to test it.

**Comment by ZerooCool** [comment]
Ok, i look that, ASAP.

**Comment by shisyamo** [comment]
Hi @alexandermeindl,
Excuse me.

Thank you very much for your correction.
I'm thinking this plug-in to apply.

But when the plug-in to which this correction was applied is carried out, an error occurs and the following log is output.

```
RuntimeError (can't modify frozen String):

plugins/redmine_messenger/app/models/messenger.rb:15:in `gsub!'
plugins/redmine_messenger/app/models/messenger.rb:15:in `markup_format'
plugins/redmine_messenger/lib/redmine_messenger/patches/issue_patch.rb:113:in `send_messenger_mention_url'
plugins/redmine_messenger/lib/redmine_messenger/patches/issue_patch.rb:48:in `send_messenger_create'
app/controllers/issues_controller.rb:133:in `create'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

```
Because it's output with "frozen String".

      text.gsub! ('&', '&amp;')
      text.gsub! ('<', '&lt;')
      text.gsub! ('>', '&gt;')

The gsub! which is so I think a text object is because it's frozen at the time of function execution.
Can't I have the advice which doesn't show solution method?

The execution environment is as follows.

Redmine version                4.1.0.stable
Ruby version                   2.4.9-p362 (2019-10-02) [x86_64-linux-gnu]
Rails version                  5.2.4.1

**Comment by alexandermeindl** [comment]
Hi @shisyamo 
thanks for reporting this! I fixed it with my last commit. It would be nice, if you could check it again.

**Comment by shisyamo** [comment]
Hi @alexandermeindl,

I checked the operation by the last commit.

An error doesn't occur and a plug-in has started.
It could also be confirmed that a message is sent to robotchat.

I'm thankful for quick correspondence.

**Comment by ZerooCool** [comment]
Ok, work for me, too !
Resolved.
